### ISSUE TITLE
Videos playbackStatus never changes

### ISSUE THREAD

**Issue by AndrewSB** [Matheus-0/Anime-Twist#4]
Hey! I was taking a look at this on an iOS simulator, as far as I can tell, the videos don't seem to play.

The urls seem to come in (something like https://twistcdn.bunny.sh/anime/akagaminoshirayukihime/[HorribleSubs] Akagami no Shirayukihime - 06 [720p].mp4) to be set on the `expo-av.Video` element, but `handleOnPlaybackStatusUpdate` never seems to be called in the `AnimeScreen`. Is that expected?

**Comment by Matheus-0** [comment]
Hi! Indeed, the video doesn't seem to play on iOS, I didn't notice this before because I focused the development on Android (since I made this app for personal use).

I suspect that iOS can't play videos when I set headers for it, I'm not sure yet. I made a [Snack example](https://snack.expo.io/@gwynn/smiling-pudding) to play 2 videos, one is from the link you mentioned, using the necessary headers and the other is the same episode from another source that doesn't require headers, the second one plays just fine on iOS.

I posted a topic on Expo forums (still waiting for it to be reviewed) about this to see if this is an Expo problem, I'll get back to you when I find out more.
